config.go

This adds support for `requirements.txt` and using external libraries in `python`.
Here's an example using `bottle` for more complex routing (JSON responses, etc ...): 
```py
import os
from bottle import route, run, template
@route('/')
def hello():
return "hello"
@route('/hello/<name>')
def hello(name):
return template('Hello <b>{{name}}</b>!', name=name)
run(port=int(os.environ.get('PORT', 8080)))
```
Similar to the current python example (slightly simpler/shorter with `bottle`):
```py
import os
from bottle import route, run
@route('/')
def hello():
return "Hello World from Python"
run(port=int(os.environ['PORT']))
```
https://ae2t1y6bfc.execute-api.eu-west-1.amazonaws.com/development/hello/TJ

Feature: support python projects with a requirements.txt

---

platform/lambda/lambda.go

Not all projects are APIs and for those that include `-api` in their project names, it's then doubled in name of the IAM roles.

Remove api assumption from IAM role

---

Makefile

I use Go 1.8 for most work stuff, so I _shouldn't_ install 1.9 as my default Go version. This patch enables me to run `make` commands with [go1.9rc2](https://golang.org/dl/#go1.9rc2) simply and doesn't require any aliasing hacks.

Makefile: allow overriding default "go" program

---

internal/zip/zip.go

Relies on https://github.com/tj/go-archive/pull/3
Also gives lower presence to `.upignore` after the UX step; see #84
fixes #50

Improve filtering/prioritization via tj/go-archive

---

.gitignore
Gopkg.lock
config.go
config_test.go

Close https://github.com/apex/up/issues/250.
If `regions` is not present in `up.json` delegates default region to aws sdk. More info about how this process works can be found [here](https://godoc.org/github.com/aws/aws-sdk-go/aws/session#hdr-Shared_Config_Fields) and [here](https://godoc.org/github.com/aws/aws-sdk-go/aws/session#hdr-Environment_Variables). Also the added [tests](https://github.com/apex/up/pull/255/files#diff-fb6a7899d06670e0e85669d2652ba911R154) try to enumerate them all.

Delegate default region to aws sdk

---

config/relay.go
http/relay/relay.go

This is for issue #264 
I kept 5 seconds as the default time if it fails to parse the time that they give. This relies on time.ParseDuration() which means you format it with a unit suffix (`Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"`). Didn't have time to test it but I'm sure it'll work 👍

Made changes to have a configurable timeout (not tested)

---

docs/04-configuration.md

As I was going through the configuration doc I noticed some number suffixes were missing from some regions. I used [the AWS docs](http://docs.aws.amazon.com/general/latest/gr/rande.html#lambda_region) to verify that the numbers I added were correct for each location.

docs: add missing numbers to regions in the configuration doc

---

Makefile
config/static_test.go

Fixed the reference to `gt` in the Makefile and have added some tests for config/static. 
One thing i didn't understand was to ignore errors to non-existent directories in https://github.com/apex/up/blob/master/config/static.go#L28-L30. What is the particular use case?

test: add tests cases for static config

---

install.sh

The new release 0.2.4 rename the checksum file to up_{version}_checksum however `install.sh` still use the old name, hence throw 404 error when we trying install or upgrade.
This pull request change the checksum in `install.sh` to match the checksum file in release.
fixes #330 
fixes #329

Change checksum name. 

---

docs/03-getting-started.md

Was preventing hello-world python example from working properly.
```
hello-world-python$ up logs
11:27:25am FATA error: initializing relay: waiting for http://127.0.0.1:38549 to be in listening state: timed out after 15s
11:27:25am INFO starting name: task type: server
11:28:14am INFO found free port 40745 version: $LATEST
11:28:14am INFO executing "python app.py" version: $LATEST
11:28:14am INFO proxy (pid=12) started version: $LATEST
11:28:14am INFO waiting for http://127.0.0.1:40745 to listen (timeout 15s) version: $LATEST
11:28:14am ERRO   File "app.py", line 6
self.send_response(200)
^
11:28:29am INFO starting name: task type: server
11:28:29am INFO found free port 41113 version: $LATEST
11:28:29am INFO executing "python app.py" version: $LATEST
11:28:29am INFO proxy (pid=12) started …
```

docs: change app.py indentation to fix problem under do_GET function

---

http/relay/relay.go
http/relay/relay_test.go
internal/proxy/request.go

I expect the `DisableKeepAlives` change to eliminate the EOF / conn reset errors.  Without those errors we would never have found the re-read request body error, which is explicitly addressed by the new `GetBody` code.
A few justifications for the other changes:
1. remove all http.Transport timeouts.  These are generally to prevent "bad" upstream servers, but I think up should try to be as invisible as possible, including not adding additional http timeouts.  We do not know how people will use Up. Maybe they want to use it for delayed `Continue` responses.
1. remove specific `GetBody` code, this is already handled by [http.NewRequest](https://golang.org/src/net/http/request.go?s=25171:25240#L811)
1. Tests show new behavior for disabling keep-alives

relay: disable keep alive conns, they interact poorly with suspension

---

Makefile

so it wont show the Makefile in the list because of the `TODO:.*|SkipNow` :)
BTW I'm totally copying this!

exclude Makefile from todo target

---

config.go

This change provides out of the box support for the Java runtime. It includes being able to build the Java project via Gradle or Maven as well as their respective wrappers (`gradlew` or `mvnw`). If a file named `pom.xml` is found in the project root directory it's assumed the project can be built via Maven. If a file named `build.gradle` is found it's assumed the project is built via Gradle.
There are a couple of assumptions:
1. The Java project will produce a shaded jar with the name `server.jar`.
2. The artifact produced can be run (on port 3000 by default) via `java -jar server.jar`

add first class support for Java runtime #390

---

docs/04-configuration.md

Changes default lambda.memory to match change in 25fa10ea5e405f169fe48dff9f04970de6a3f126

docs: change default lambda.memory

---

reporter/text/text.go

refactor: drop unnecessary fmt.Sprintf in reporter/text

---

platform/lambda/stack/stack.go

`time.Tick` leaks its goroutine since it's not manageable. Instead, new ticker is created and deferred to stop as soon as function returns.

fix: goroutine leak in lambda report

---

internal/logs/parser/ast/ast.go
platform/lambda/cost/cost.go

Tiny improvements:
* type conversion: constants are typeless
* function call: no need to pipe string to `fmt.Sprintf`

refactor: remove unnecessary parts

---

internal/zip/zip.go

As discuted in https://github.com/apex/up-examples/issues/60 Gradle based projects can not run.
The build.gradle file is always excluded from the out.zip file.
This PR allows to include build.gradle in out.zip.

fix: add a ! in front of build.gradle

---

config.go
internal/zip/zip.go

This PR provides native Clojure support for Up with zero configuration. Here's an example project:
https://github.com/rads/up-clojure/tree/native

Add support for Clojure with Leiningen

---

docs/06-commands.md

Just a simple documentation change.

Fix typo in `up start` command documentation

---

internal/userconfig/userconfig.go

This is meant to address #593 and since it was trivial to implement I decided to open a PR where discussion could also take place.
When loading config via `$UP_CONFIG`, it will check to see if the value is JSON. If not, it will attempt to base64-decode that string before attempting to unmarshal as JSON.

change UP_CONFIG to attempt base64-decode when not JSON

---

docs/04-configuration.md

Bit faster than going through docs line-by-line, hitting this error, and being redirected to the related issue.

docs: Move warning about glob regions up a bit

---

cmd/up/main.go
internal/cli/disable-stats/disable-stats.go

As discussed on Slack, I'm unable to send anonymized usage stats for various reasons. This patch makes disabling the stats much easier, as no prior knowledge of `go-cli-analytics` is required.

add hidden disable stats command

---

config/runtimes.go
docs/05-runtimes.md

Crystal build uses PWD instead of pwd, which fails on case-sensitive operating systems and filesystems, e.g. Linux

Fix Crystal build on Linux: PWD => pwd

---

docs/04-configuration.md

docs: fix typo in configuration

---

docs/06-commands.md

According to other parts of the documentation and also according to the code the default stage is "staging" and not "development".
See code at latest commit for that file: https://github.com/apex/up/blob/6d27f34c95c7eeba660d54a8ff7c6e48c69f6769/internal/cli/deploy/deploy.go#L22
Note: Only the PR header contains the "docs: " prefix. Is this enough for the filtering of the release notes, or do I need to change the commit?

docs: Fix default stage of "up" and "up deploy"

---

docs/02-aws-credentials.md

When you click on "Show policy" it wasn't formatting the `json` code block correctly before. The newlines seem to fix that.

Fix json code block

---

docs/07-guides.md

Open an issue and discuss changes before spending time on them, unless the change is trivial or an issue already exists.
Use "VERB some thing here. Closes #n" to close the relevant issue, where VERB is one of:
- add
- remove
- change
- refactor
If the change is documentation related prefix with "docs: ", as these are filtered from the changelog.
docs: add ~/.aws/config
Run `dep ensure` if you introduce any new `import`'s so they're included in the ./vendor dir.

docs: fix typo in guides.md

---

docs/06-commands.md
docs/07-guides.md

There seems to be some documentation drift between "development" and "staging" environments.
Sometimes the subdomain is `stage.` 
```
Staging
domain: stage.up-example.com
```
...and other's it's `dev.`
```
"stages": {
"staging": {
"domain": "dev.up-example.com"
},
```
Minor changes:
* Change all occurrences of "development" to "staging" when it comes to
the default `up` commands.
* Update all `dev.` URLs to `stage.`

Update references to Staging in docs

---

CONTRIBUTING.md
platform/lambda/lambda.go
platform/lambda/lambda_test.go

See https://github.com/apex/up/issues/787 for more details.

Change stack delete behavior to not attempt to delete configured lambda roles. (Closes #787)
